version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - .env.database
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the init script
    networks:
      - wps

  web:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - wps

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - "8081:80"
    env_file:
      - .env.database
    restart: "no"

networks:
  wps:
